Animal/urls.py
from django.urls import path

from .views import all_animals, add_Animal, Animal_detail, editAnimal, deleteAnimal, export_pdf, export_excel

app_name = 'Animal'

urlpatterns = [
    path('', all_animals, name='all_animals'),
    path('add_Animal/', add_Animal, name='add_Animal'),
    path('animal_detail/<int:id>', Animal_detail, name='animal_detail'),
    path('editAnimal/<str:id>', editAnimal, name='editAnimal'),
    path('deleteAnimal/<str:id>', deleteAnimal, name='deleteAnimal'),
    path('export_pdf', export_pdf, name='export_pdf'),
    path('export_excel', export_excel, name='export_excel'),
]

BaitHam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from adopter import views

app_name = 'adopter'

urlpatterns = [
    path('admin/',admin.site.urls),
    path('', views.home, name='home'),
    path('admin_page/', views.admin, name='admin_page'),
    path('reports',views.reports,name='reports'),
    path('adopter/', views.contact_us, name='contact_us'),
    path('Report/',include('Report.urls')),
    path('Article/',include('Article.urls')),
    path('success_story/',include('success_story.urls')),
    path('Animal/',include('Animal.urls'), name='Animal'),
    path('volunteer/',include('volunteer.urls')),
    path('Event/',include('Event.urls')),
    path('Donations/',include('Donations.urls'), name='Donations)'),
    path('forum/', include('forum.urls'), name='forum'),
    path('Taskboard/',include('Taskboard.urls'), name='Taskboard)'),
    path('Supplier/',include('Supplier.urls'),name='Supplier'),
    path('Stock/',include('Stock.urls'),name='Stock'),
    path('contact_us/',views.contact_us,name='contact_us'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Event/urls.py
from django.urls import path
from . import views

app_name = 'Event'

urlpatterns = [
    path('all_events/', views.all_events, name='all_events'),
    path('createEvent/', views.createEvent, name='createEvent'),
    path('deleteEvent/<event_id>', views.deleteEvent, name='deleteEvent'),
    path('event_detail/<int:id>', views.Event_detail, name='Event_detail'),
    path('export_pdf', views.export_pdf, name='export_pdf'),
    path('export_excel', views.export_excel, name='export_excel'),
]

Animal/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from datetime import date


def validate_month(value):
    if not 1 <= value < 12:
        raise ValidationError(
            _('%(value)s is not a valid month'),
            params={'value': value},
        )


class animal(models.Model):
    Sex_Choice = [('M', 'זכר'), ('F', 'נקבה')]
    Species_choice = [('dog', 'כלב'), ('cat', 'חתול')]
    Adoption_ready = [('N', 'לא'), ('Y', 'כן')]

    name = models.CharField(max_length=100, verbose_name="שם")  # Name of the Pet
    submitter = models.CharField(max_length=100, null=True, verbose_name="הוכנס על ידי")  # Name of Submitter
    species = models.CharField(max_length=30, choices=Species_choice, blank=False,
                               default='Dog', verbose_name="סוג")  # What is the Pet species? (dog, cat)
    breed = models.CharField(max_length=30, blank=False, verbose_name="גזע")  # Pet's breed
    description = models.TextField(blank=False, verbose_name="תיאור")  # Description like where was found etc...
    sex = models.CharField(max_length=30, choices=Sex_Choice, default='M', blank=False, verbose_name="מין")  # Gender
    submission_date = models.DateTimeField(auto_now_add=True, verbose_name="תאריך קליטה")  # Date submitted to shelter
    image = models.ImageField(upload_to='Animal', blank=True, default='default.png',
                              verbose_name="העלאת תמונה")  # for animal images
    Adoption = models.CharField(max_length=30, choices=Adoption_ready, blank=False, default='No',
                                verbose_name="מוכן לאימוץ")  # adoption filter

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "מאגר בעלי חיים"


class Stats(models.Model):
    created = models.IntegerField(blank=True, default=0)
    deleted = models.IntegerField(blank=True, default=0)
    current = models.IntegerField(blank=True, default=0)
    month = models.IntegerField(blank=True, default=1, validators=[validate_month])

    class Meta:
        verbose_name_plural = "סטטיסטיקה"

Animal/forms.py
from django.forms import ModelForm, Form
from django import forms

from .models import animal


class Add_Animal_Form(ModelForm):
    class Meta:
        model = animal
        fields = ['name', 'submitter', 'species', 'breed', 'description', 'sex', 'Adoption', 'image']
        widgets = {
        'description': forms.Textarea(attrs={'placeholder': 'הכנס תיאור מפורט ככל הניתן'}),
        }

Animal/views.py
from django.shortcuts import render, redirect
from Animal.forms import Add_Animal_Form
from .models import animal, Stats
from .filters import animalFilter
from django.http import HttpResponse, FileResponse
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
import io
import xlwt


def all_animals(request):
    if request.user.is_authenticated:
        animals = animal.objects.all()
    else:
        animals = animal.objects.filter(Adoption='Y')

    myfilter = animalFilter(request.GET, queryset=animals)
    animals = myfilter.qs
    context = {'animals': animals, 'myfilter': myfilter}

    return render(request, 'Animal/all_animals.html', context)


def add_Animal(request):
    ''' the function will add animal to the database using a form '''
    if request.method == 'POST':
        form = Add_Animal_Form(request.POST, request.FILES)
        if form.is_valid():  # data validation
            form.save()
            stat = Stats.objects.last()
            stat.created += 1  # statistics updating
            stat.current = animal.objects.count()  # statistics updating
            stat.save()
            return redirect('Animal:all_animals')
    # GET or Not valid form
    return render(request, 'Animal/add_Animal.html', {'form': Add_Animal_Form()})


def Animal_detail(request, id):
    ''' function to get an id of a specific animal and send all the info on it'''
    animal_obj = None
    if id is not None:
        animal_obj = animal.objects.get(id=id)  # getting the right animal
    context = {"object": animal_obj}
    return render(request, 'Animal/animal_detail.html', context=context)  # sending the info


def editAnimal(request, id=None):
    ''' function to edit the info of a specific animal '''
    if id is not None:
        animal_up = animal.objects.get(id=id)  # getting the right animal
        form = Add_Animal_Form(instance=animal_up)  # showing the form filled with the animal info
        if request.method == 'POST':  # after pressing add we get the update info
            form = Add_Animal_Form(request.POST, request.FILES, instance=animal_up)
            if form.is_valid():
                form.save()
                return redirect('Animal:all_animals')
        context = {"form": form}
        return render(request, 'Animal/add_Animal.html', context=context)

    return redirect('Animal:all_animals')  # in the case of bad id sent here


def deleteAnimal(requset, id):
    ''' uction to delete an animal object by its id '''
    animal_obj = animal.objects.get(id=id)
    if requset.method == 'POST':
        if animal_obj.image and animal_obj.image != 'default.png':
            animal_obj.image.delete()
        animal_obj.delete()

        stat = Stats.objects.last()
        stat.deleted += 1
        stat.current = animal.objects.count()
        stat.save()
        return redirect('Animal:all_animals')

    context = {'animal': animal_obj}
    return render(requset, 'Animal/DeleteAnimal.html', context)


def export_pdf(request):
    """Function for exporting a pdf document from the system"""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)  # creat a new page
    textob = c.beginText()  # creat a text object
    textob.setTextOrigin(inch, inch)  # set the sizes of the text
    pdfmetrics.registerFont(TTFont('David', 'David.ttf'))
    textob.setFont("David", 14)  # set the font of the text

    stats = Stats.objects.all()  # designate the model
    lines = []  # creat a new list for the objects

    # print all data we need
    for stat in stats:
        lines.append('Month number:' + str(stat.month))
        lines.append('Entered the hoard: ' + str(stat.created))
        lines.append('Current amount: ' + str(stat.current))
        lines.append('Animals adopted: ' + str(stat.deleted))
        lines.append('    ')
        lines.append('_______________________________________')
        lines.append('    ')

    textob.textLine("Association Status Report (Changes in Quantities) for 2021")  # the title of the file
    textob.textLine("    ")
    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()  # save the file
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename='status.pdf')


def export_excel(request):
    """Function for exporting an excel document from the system"""
    response = HttpResponse(content_type='status/excel')
    response['Content-Disposition'] = 'attachment; filename=status' + str(datetime.now()) + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('status')  # give a name to the sheet
    row_num = 2  # initial row for objects
    font_style = xlwt.XFStyle()  # set the font of the text
    font_style.font.bold = True

    ws.write(0, 0, 'Association Status Report (Changes in Quantities) for 2021', font_style)  # the title of the file

    columns = ['Month number', 'Entered the hoard', 'Current amount', 'Animals adopted']  # the columns in the table

    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    # save all the data we need from database
    rows = Stats.objects.all().values_list('month', 'created', 'current', 'deleted')

    font_style = xlwt.XFStyle()

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, str(row[col_num]), font_style)  # enter all the data to the table

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    wb.save(response)  # save the file

    return response

Animal/templates/Animal/DeleteAnimal.html
{% extends "adopter/Base.html" %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <p> האם אתה בטוח שברצונך למחוק את {{ animal }} ?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <a href="{% url 'Animal:animal_detail' animal.id %}" class="btn btn-danger">בטל</a>
    <input type="submit" class="btn btn-dark" name="מאשר">
    </form>
{% endblock %}

Animal/templates/Animal/add_Animal.html
{% extends 'adopter/home.html' %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<head>
<style>
h1 {text-align: center;}
p {text-align: center;}
div {text-align: -webkit-center;}

</style>
</head>

<body>
<div>
    <h1>הוספת בעל חיים למאגר</h1>
    <br>
    <form action="" class="form-horizontal form_middle" enctype='multipart/form-data' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">הוסף</button>
    </form>
</div>
 {% endblock %}

Animal/templates/Animal/all_animals.html
{% extends "adopter/Base.html" %}

{% load static %}

{% block content %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <head>
        <style>
            h1 {
                text-align: center;
            }

            p {
                text-align: center;
            }

            div {
                text-align: center;
            }

        </style>
    </head>

    {% if user.is_authenticated %}
    <b>מחובר בתור {{user.username}}</b>
    {% endif %}

    <br>
    <br>
<body>
<br>
<h1 class="font-weight-bold text-center"> מאגר בעלי החיים שלנו </h1>

        <br>

        <form method="GET" >
            <b>חיפוש מתקדם:</b>
            <br>
            {{ myfilter.form }}
            <button class='btn btn-outline-dark' type="submit">חפש</button>
        </form>

    <div class="row"/>

    <div>
        {% if user.is_authenticated %}
            <br>
            <a role="button" href="{% url 'Animal:add_Animal' %} " class="btn btn-dark">הוסף בעל חיים למאגר</a>
            <br>
            <br>
        {% endif %}
    </div>
    <br>
    <br>
    <br>


    {% for animal in animals %}
        <div class="col-lg-4 col-md-6">

            <h5><b>{{ animal.name }}</b></h5>
            <a href="{% url 'Animal:animal_detail' animal.id %}">
                <img src={% if animal.image %}
                    {{ animal.image.url }}
                {% endif %}
                             class="rounded" height=300 width=300></a>
            <b><p>{{ animal.description }}</p></b>

            <a role="button" href="{% url 'Animal:animal_detail' animal.id %}" class="btn btn-secondary">לפרטים מלאים
                עליי</a>
            <br>
            <br>


        </div>
        </body>
    {% endfor %}

{% endblock %}

Animal/templates/Animal/animal_detail.html
{% extends "adopter/Base.html" %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<head>
    <style>
        h1 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        div {
            text-align: center;
        }

    </style>
    <meta charset="UTF-8">
    <title>{{object.name}}</title>
</head>

    {% if user.is_authenticated %}
        <a role="button" href="{% url 'Animal:editAnimal' object.id %}" class="btn btn-secondary">ערוך</a>
        <a role="button" href="{% url 'Animal:deleteAnimal' object.id %}" class="btn btn-secondary">הסר</a>
    {% endif %}

<br>
    <br>
<h3><b>{{object.name}}</b></h3>
 <img  src={% if object.image %}
                {{ object.image.url }}
        {% else %}
                "media/default.png"
        {% endif %}
          class="rounded" height=300 width=300 alt="{{ animal.name }}"><br>
    <br>
    <br>
    <ins><h4>קצת פרטים עליי</h4></ins>
<b>{{object.description | linebreaks}}</b> <br><br>

<b>גזע: {{object.breed}}</b> <br><br>

<p>{% if object.sex == 'M' %}</p>
<b> מין: זכר</b><br><br>
{% else %}
<b> מין: נקבה</b><br><br>
{% endif %}
<a role="button" href="{% url 'contact_us' %}" class="btn btn-secondary">אמצו אותי</a>

{% endblock content %}