BaitHam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from adopter import views

app_name = 'adopter'

urlpatterns = [
    path('admin/',admin.site.urls),
    path('', views.home, name='home'),
    path('admin_page/', views.admin, name='admin_page'),
    path('reports',views.reports,name='reports'),
    path('adopter/', views.contact_us, name='contact_us'),
    path('Report/',include('Report.urls')),
    path('Article/',include('Article.urls')),
    path('success_story/',include('success_story.urls')),
    path('Animal/',include('Animal.urls'), name='Animal'),
    path('volunteer/',include('volunteer.urls')),
    path('Event/',include('Event.urls')),
    path('Donations/',include('Donations.urls'), name='Donations)'),
    path('forum/', include('forum.urls'), name='forum'),
    path('Taskboard/',include('Taskboard.urls'), name='Taskboard)'),
    path('Supplier/',include('Supplier.urls'),name='Supplier'),
    path('Stock/',include('Stock.urls'),name='Stock'),
    path('contact_us/',views.contact_us,name='contact_us'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Event/urls.py
from django.urls import path
from . import views

app_name = 'Event'

urlpatterns = [
    path('all_events/', views.all_events, name='all_events'),
    path('createEvent/', views.createEvent, name='createEvent'),
    path('deleteEvent/<event_id>', views.deleteEvent, name='deleteEvent'),
    path('event_detail/<int:id>', views.Event_detail, name='Event_detail'),
    path('export_pdf', views.export_pdf, name='export_pdf'),
    path('export_excel', views.export_excel, name='export_excel'),
]

Report/urls.py
from django.urls import path
from . import views

app_name = 'Report'

urlpatterns = [
    path('all_reports/', views.all_reports, name='all_reports'),
    path('createReport/', views.createReport, name='createReport'),
    path('deleteReport/<report_id>', views.deleteReport, name='deleteReport'),
]

Report/models.py
from django.db import models
from datetime import date


# create a new model for report app

class report(models.Model):
    date = models.DateField(default=date.today, verbose_name="תאריך ")  # date of the report
    name = models.CharField(max_length=100, verbose_name="שם המדווח ")  # name of the reporter
    text = models.TextField(blank=True, verbose_name="תוכן הדיווח ")  # the content of the report

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "דיווחים"

Report/forms.py
from django.forms import ModelForm
from .models import report


class ReportForm(ModelForm):
    class Meta:
        model = report
        fields = ['date', 'name', 'text']

Report/views.py
from django.shortcuts import render, redirect
from .models import report
from .forms import ReportForm


def createReport(request):
    """the function creat a new report according to the request of the user and save it in the database"""
    if request.method == 'POST':
        form = ReportForm(request.POST)  # creat a form for the report
        if form.is_valid():
            new_report = form.save(commit=False)
            new_report.save()  # saving the new report in the database
            return redirect('Report:all_reports')  # refers to the page of all reports
    return render(request, 'Report/createReport.html', {'form': ReportForm()})


def all_reports(request):
    """the function presents all reports in the order of their arrival"""
    reports = report.objects.order_by('-date')
    return render(request, 'Report/all_reports.html', {'reports': reports})


def deleteReport(request, report_id):
    """the function delete a report according to the request of the user (volunteer only) and delete it
     from the database """
    Report = report.objects.get(pk=report_id)
    Report.delete()  # delete the report from the database
    return redirect('Report:all_reports')  # refers to the page of all reports

Report/templates/Report/all_reports.html
{% extends "adopter/base.html" %}

{% load static %}

{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<html>
<head>
    <style>
        h1 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        div {
            text-align: center;
        }
    </style>
</head>

{% if user.is_authenticated %}
    <b>מחובר בתור {{user.username}}</b>
    {% endif %}
    <br>
    <br>

<body>

<h1 class="font-weight-bold text-center"> דיווחים אחרונים </h1>

<h3 class="text-center mb-5"> משתמשים הוסיפו עד כה {{ reports.count }} דיווחים </h3>

{% for report in reports %}
<div class="row justify-content-center my-3">
    <div class="col-md-10">
        <h5 class="text-muted">{{ report.date|date:'d/m/Y'|upper }}</h5>
        <h2>{{ report.name }}</h2>
        <p>{{ report.text|striptags}}</p>
        {% if user.is_authenticated %}
        <a href="{% url 'Report:deleteReport' report.id %}" class="btn btn-dark">נאסף</a>
        {% endif %}
    </div>
</div>

{% endfor %}

    <br>
    <br>
    {% if user.is_authenticated %}
    <a role="button" href="{% url 'Report:createReport' %}" class="btn btn-warning">להוספת דיווח נוסף</a>
    {% endif %}
    <br>
    <br>
{% endblock %}

Report/templates/Report/createReport.html
{% extends 'adopter/Base.html' %}
{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!doctype html>
<html lang="he" dir="rtl">

    <html>
<head>
<style>
h1 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>
</head>
<body>

    <h1>דיווח על בע"ח נטושים</h1>
    <br>
    <form method="POST">
        {% csrf_token %}
    {{ form.as_p }}

        <button type="submit" class="btn btn-dark">דווח</button>
    </form>

 {% endblock %}