Animal/urls.py
from django.urls import path

from .views import all_animals, add_Animal, Animal_detail, editAnimal, deleteAnimal, export_pdf, export_excel

app_name = 'Animal'

urlpatterns = [
    path('', all_animals, name='all_animals'),
    path('add_Animal/', add_Animal, name='add_Animal'),
    path('animal_detail/<int:id>', Animal_detail, name='animal_detail'),
    path('editAnimal/<str:id>', editAnimal, name='editAnimal'),
    path('deleteAnimal/<str:id>', deleteAnimal, name='deleteAnimal'),
    path('export_pdf', export_pdf, name='export_pdf'),
    path('export_excel', export_excel, name='export_excel'),
]

Article/urls.py
from django.urls import path
from .views import all_articles


app_name = 'Article'

urlpatterns = [

    path('articles/', all_articles, name='articles'),

]

BaitHam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from adopter import views

app_name = 'adopter'

urlpatterns = [
    path('admin/',admin.site.urls),
    path('', views.home, name='home'),
    path('admin_page/', views.admin, name='admin_page'),
    path('reports',views.reports,name='reports'),
    path('adopter/', views.contact_us, name='contact_us'),
    path('Report/',include('Report.urls')),
    path('Article/',include('Article.urls')),
    path('success_story/',include('success_story.urls')),
    path('Animal/',include('Animal.urls'), name='Animal'),
    path('volunteer/',include('volunteer.urls')),
    path('Event/',include('Event.urls')),
    path('Donations/',include('Donations.urls'), name='Donations)'),
    path('forum/', include('forum.urls'), name='forum'),
    path('Taskboard/',include('Taskboard.urls'), name='Taskboard)'),
    path('Supplier/',include('Supplier.urls'),name='Supplier'),
    path('Stock/',include('Stock.urls'),name='Stock'),
    path('contact_us/',views.contact_us,name='contact_us'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Event/urls.py
from django.urls import path
from . import views

app_name = 'Event'

urlpatterns = [
    path('all_events/', views.all_events, name='all_events'),
    path('createEvent/', views.createEvent, name='createEvent'),
    path('deleteEvent/<event_id>', views.deleteEvent, name='deleteEvent'),
    path('event_detail/<int:id>', views.Event_detail, name='Event_detail'),
    path('export_pdf', views.export_pdf, name='export_pdf'),
    path('export_excel', views.export_excel, name='export_excel'),
]

Report/urls.py
from django.urls import path
from . import views

app_name = 'Report'

urlpatterns = [
    path('all_reports/', views.all_reports, name='all_reports'),
    path('createReport/', views.createReport, name='createReport'),
    path('deleteReport/<report_id>', views.deleteReport, name='deleteReport'),
]

Stock/urls.py
from django.urls import path
from . import views

app_name = 'Stock'

urlpatterns = [

    path('export_pdf', views.export_pdf, name="export_pdf"),
    path('export_excel', views.export_excel, name="export_excel"),
    path('selectStock/', views.selectStock, name='selectStock'),
    path('updateStock/<str:id>', views.updateStock, name='updateStock'),

]

forum/urls.py
from django.urls import path, re_path

from .views import addInForum, addInDiscussion, home

app_name = 'forum'

urlpatterns = [
    path('home/', home, name='home'),
    path('addInForum/', addInForum, name='addInForum'),
    path('addInDiscussion/', addInDiscussion, name='addInDiscussion'),

]

Report/models.py
from django.db import models
from datetime import date


# create a new model for report app

class report(models.Model):
    date = models.DateField(default=date.today, verbose_name="תאריך ")  # date of the report
    name = models.CharField(max_length=100, verbose_name="שם המדווח ")  # name of the reporter
    text = models.TextField(blank=True, verbose_name="תוכן הדיווח ")  # the content of the report

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "דיווחים"

Report/forms.py
from django.forms import ModelForm
from .models import report


class ReportForm(ModelForm):
    class Meta:
        model = report
        fields = ['date', 'name', 'text']

Report/views.py
from django.shortcuts import render, redirect
from .models import report
from .forms import ReportForm


def createReport(request):
    """the function creat a new report according to the request of the user and save it in the database"""
    if request.method == 'POST':
        form = ReportForm(request.POST)  # creat a form for the report
        if form.is_valid():
            new_report = form.save(commit=False)
            new_report.save()  # saving the new report in the database
            return redirect('Report:all_reports')  # refers to the page of all reports
    return render(request, 'Report/createReport.html', {'form': ReportForm()})


def all_reports(request):
    """the function presents all reports in the order of their arrival"""
    reports = report.objects.order_by('-date')
    return render(request, 'Report/all_reports.html', {'reports': reports})


def deleteReport(request, report_id):
    """the function delete a report according to the request of the user (volunteer only) and delete it
     from the database """
    Report = report.objects.get(pk=report_id)
    Report.delete()  # delete the report from the database
    return redirect('Report:all_reports')  # refers to the page of all reports

adopter/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from Animal.models import animal
from Event.models import event


def home(request):
    events =  event.objects.all().order_by('-id')[:2]
    if request.user.is_authenticated:
        animals = animal.objects.all()
    else:
        animals = animal.objects.filter(Adoption='Y')
    return render(request, 'adopter/home.html', {'animals': animals, 'events': events})


def reports(request):
    return render(request, 'adopter/reports.html')


def admin(request):
    return HttpResponseRedirect(reverse('admin:index'))


def contact_us(request):
    return render(request, 'adopter/contact_us.html')

adopter/templates/adopter/Base.html
{% load static %}

<!doctype html>
<html lang="he" dir="rtl">

<head>

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<link rel="stylesheet" href="{% static 'adopter/custom.css ' %}">

<link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

<link rel="icon" type="image/png" href="{% static 'adopter/Logo.jpeg' %}">

<title>בית חם</title>

</head>



<body>
<nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">

        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'adopter/Logo.jpeg' %}" width="70" height="40" class="d-inline-block align-top"
                 alt="BaitHam's Logo">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">

                <li>
                <a role="button" href="{% url 'Article:articles' %}" class="btn btn-info">מאמרים</a>
                </li> &#160
                <li>
                    <a role="button" href="{% url 'forum:home' %}" class="btn btn-info">פורום</a>
                </li>
                &#160

                <li>
                    <a role="button" href="{% url 'Event:all_events' %}" class="btn btn-info">אירועים</a>
                </li>
                &#160
                <li>
                    <a role="button" href="{% url 'success_story:all_stories' %}" class="btn btn-info">סיפורי הצלחה</a>
                </li>
                &#160
                <li>
                    <a role="button" href="{% url 'Animal:all_animals' %}" class="btn btn-info">בעלי חיים</a>
                </li>
                &#160
            {% if not user.is_authenticated %}
                <li>
                    <a role="button" href="{% url 'Donations:new' %}" class="btn btn-info">תרומות</a>
                </li>
                &#160
            {% endif %}
                <li>
                    <a role="button" href="{% url 'reports' %}" class="btn btn-info">דו"חות</a>
                </li>
                &#160


                {% if user.is_authenticated and not user.is_superuser %}
                    <li>
                        <a role="button" href="{% url 'volunteer:update' %}" class="btn btn-info">דיווח נוכחות</a>
                    </li>&#160
                    {% endif %}
                {% if user.is_authenticated %}
                    <li>
                        <a role="button" href="{% url 'Taskboard:all_task' %}" class="btn btn-info">לוח מטלות</a>
                    </li> &#160

                    <li>
                        <a role="button" href="{% url 'Stock:selectStock' %}" class="btn btn-info">עדכון מלאי</a>
                    </li> &#160

                    <li>
                        <a role="button" href="{% url 'Report:all_reports' %}" class="btn btn-danger">דיווחים מהשטח</a>
                    </li>&#160

                    <li>
                        <form class="logout-link" action="{% url 'volunteer:logoutuser' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark">התנתק</button>
                        </form>
                    </li> &#160

                {% else %}

                    <li>
                        <a role="button" href="{% url 'contact_us' %}" class="btn btn-info">צור קשר</a>
                    </li>&#160
                    <li>
                        <a role="button" href="{% url 'Report:createReport' %}" class="btn btn-danger">כפתור אדום</a>
                    <li>&#160

                    <li>
                        <a role="button" href="{% url 'volunteer:loginuser' %}" class="btn btn-dark">התחבר</a>
                    </li>&#160
                {% endif %}

                {% if user.is_authenticated and user.is_superuser %}
                        <a role="button" href="{% url 'admin_page' %}" class="btn btn-secondary">ניהול</a>
                    </li>&#160
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

adopter/templates/adopter/contact_us.html
{% extends "adopter/Base.html" %}

{% load static %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <center><img src="{% static 'adopter/bunner.jpeg' %}" class="img-fluid" height=800 width=800 ></center>
            <br>


   <h4> <p dir="rtl" style="text-align: center;" > <strong>תהיו בקשר!</strong></p></h4>
  <h4> <p dir="rtl" style="text-align: center;"><strong>נשמח לענות לכל פנייה בשעות פעילות</strong></p> </h4>

    <p dir="rtl" style="text-align: center;"><strong>א' - ה'</strong> 17:00 - 08:30</p>
    <p dir="rtl" style="text-align: center;"><strong>ו'</strong> 13:00 - 08:30</p>
    <p dir="ltr" style="text-align: center;"><a title="053-3333333" href="https://wa.me/972533333333" target="_blank">053-3333333</a> <strong>WhatsApp / SMS</strong></p>
    <p dir="rtl" style="text-align: center;"><strong>מייל </strong><a href="mailto:anonymous@gmail.com">anonymous@gmail.com</a></p>
    <p dir="rtl" style="text-align: center;"><strong>כתובת: </strong> רחוב סומסום 33,באר-שבע</p>


{% endblock %}

adopter/templates/adopter/home.html
{% extends "adopter/Base.html" %}

{% load static %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% if user.is_authenticated %}
    <b>מחובר בתור {{user.username}}</b>
    {% endif %}


<img src="{% static 'adopter/bunner.jpeg' %}" class="img-fluid">

<br>
<br>

    <mark><h1> מחפשים בית חם ♥</h1></mark>


<div class="row"/>
<head>

    <style>
        h1 {
            text-align: center;
        }

        p {
            text-align: center;

        }

        div {
            text-align: center;
        }
        mark {
            color: black;
            text-shadow: 2px 2px 4px #000000;
        }

        h5 {
              color: black;
              text-shadow: 2px 2px 4px #000000;
            }
    </style>
</head>


{% for animal in animals %}
    <div class="col-lg-4 col-md-6">
        <h5><b>{{ animal.name }}</b></h5>

<a href="{% url 'Animal:animal_detail' animal.id %}">
            <img src={% if animal.image %}
                {{ animal.image.url }}
            {% endif %}
                         class="rounded" height=300 width=300></a>
        <b><p>{{ animal.description }}</p></b>

        <a role="button" href="{% url 'Animal:animal_detail' animal.id %}" class="btn btn-dark">לפרטים מלאים עליי</a>
        <br>
        <br>

    </div>
{% endfor %}
            <a role="button" href="{% url 'Animal:all_animals' %}" class="btn btn-light">למאגר האימוץ המלא</a>
<br>
<br>
<br>
    <mark><h3> אירועים קרובים:</h3></mark>

{% for event in events %}
        <div class="col-lg-4 col-md-6">
<div class="row justify-content-center my-3">
    <div class="col-md-10">
         <h5><b>{{ event.name }}</b></h5>
        <h4 class="text-muted">{{ event.date|date:'D M,Y'|upper }}</h4>
        <p>{{ event.text|truncatechars:100}}</p>
        <a href="/Event/event_detail/{{event.id}} "><img  src={% if event.image %}{{ event.image.url }}{% endif %}
          class="rounded" height=300 width=400></a>
        <br>
    </div>
</div>
        </div>
    {% endfor %}
            <a role="button" href="{% url 'Event:all_events' %}" class="btn btn-light">לכל האירועים</a>

    <br>
    <br>
    <br>
{% endblock %}

adopter/templates/adopter/reports.html
{% extends "adopter/Base.html" %}

{% load static %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% if user.is_authenticated %}
    <b>מחובר בתור {{user.username}}</b>
    {% endif %}
    <br>
    <br>

    <div class="row"/>
    <head>
        <style>
            h1 {
                text-align: center;
            }

            p {
                text-align: center;
            }

            div {
                text-align: center;
            }

        </style>
    </head>
    <body>

    <br>
    <br>
    <br>
<div>
<br>
    <h1 class="font-weight-bold text-center"> הפקת דו"חות </h1>
<br>
{% if user.is_authenticated %}
</div>
    <div class="row">
        <div class="col-md">
                <table class="table table-sm">
                    <tr>
                        <th>לשימוש אישי</th>
                        <th>לשימוש עסקי\מנהלי</th>
                    </tr>


<tr>
    <th>

        <h4><b>דו"ח שעות התנדבות: </b></h4>
<a  href="{% url 'volunteer:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a  href="{% url 'volunteer:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>

<h4><b>דו"ח פיננסי (הכנסות): </b></h4>
<a href="{% url 'Donations:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a href="{% url 'Donations:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>

    <h4><b>דו"ח מצב עמותה: </b></h4>
<a  href="{% url 'Animal:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a  href="{% url 'Animal:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>

        <h4><b>דו"ח כספי: </b></h4>
<a href="https://www.guidestar.org.il/home" class="btn btn-secondary">מעבר לרשם העמותות</a> &#160
    <br>
    <br>
</th>

<th>
<h4><b>דו"ח מלאי: </b></h4>
<a  href="{% url 'Stock:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a  href="{% url 'Stock:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>

<h4><b>דו"ח ספקים: </b></h4>
<a  href="{% url 'Supplier:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a  href="{% url 'Supplier:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>


    <h4><b>דו"ח בקרת מטלות: </b></h4>
<a  href="{% url 'Taskboard:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a  href="{% url 'Taskboard:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>


        <h4><b>דו"ח פעילויות עמותה: </b></h4>
<a  href="{% url 'Event:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a  href="{% url 'Event:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>
         </tr>
</th>
            </table>
        </div>

</div>

{% else %}
        <br>

<h4><b>דו"ח פיננסי (הכנסות): </b></h4>
<a href="{% url 'Donations:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a href="{% url 'Donations:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>

    <h4><b>דו"ח מצב עמותה: </b></h4>
<a  href="{% url 'Animal:export_pdf' %}" class="btn btn-secondary">ייצא באמצעות PDF</a> &#160
<a  href="{% url 'Animal:export_excel' %}" class="btn btn-success" >ייצא באמצעות excel</a> &#160

    <br>
    <br>

    <h4><b>דו"ח כספי: </b></h4>
<a href="https://www.guidestar.org.il/home" class="btn btn-secondary">מעבר לרשם העמותות</a> &#160
    <br>
    <br>

    {% endif %}
{% endblock %}