BaitHam/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from adopter import views

app_name = 'adopter'

urlpatterns = [
    path('admin/',admin.site.urls),
    path('', views.home, name='home'),
    path('admin_page/', views.admin, name='admin_page'),
    path('reports',views.reports,name='reports'),
    path('adopter/', views.contact_us, name='contact_us'),
    path('Report/',include('Report.urls')),
    path('Article/',include('Article.urls')),
    path('success_story/',include('success_story.urls')),
    path('Animal/',include('Animal.urls'), name='Animal'),
    path('volunteer/',include('volunteer.urls')),
    path('Event/',include('Event.urls')),
    path('Donations/',include('Donations.urls'), name='Donations)'),
    path('forum/', include('forum.urls'), name='forum'),
    path('Taskboard/',include('Taskboard.urls'), name='Taskboard)'),
    path('Supplier/',include('Supplier.urls'),name='Supplier'),
    path('Stock/',include('Stock.urls'),name='Stock'),
    path('contact_us/',views.contact_us,name='contact_us'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Event/urls.py
from django.urls import path
from . import views

app_name = 'Event'

urlpatterns = [
    path('all_events/', views.all_events, name='all_events'),
    path('createEvent/', views.createEvent, name='createEvent'),
    path('deleteEvent/<event_id>', views.deleteEvent, name='deleteEvent'),
    path('event_detail/<int:id>', views.Event_detail, name='Event_detail'),
    path('export_pdf', views.export_pdf, name='export_pdf'),
    path('export_excel', views.export_excel, name='export_excel'),
]

Taskboard/urls.py
from django.urls import path
from .views import all_task, task_detail, createTask, export_pdf, export_excel, assignTask, doneTask,deleteTask

app_name = 'Taskboard'

urlpatterns = [
    path('', all_task, name='all_task'),  # View all tasks
    path('task_detail/<int:id>', task_detail, name='task_detail'),
    path('createTask/', createTask, name='createTask'),
    path('deleteTask/<task_id>', deleteTask, name='deleteTask'),
    path('export_pdf', export_pdf, name='export_pdf'),
    path('export_excel', export_excel, name='export_excel'),
    path('assignTask/<int:id>', assignTask, name='assignTask'),
    path('doneTask/<int:id>', doneTask, name='doneTask'),
]

Taskboard/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


class list_task(models.Model):
    date = models.DateField(default=date.today,verbose_name="תאריך")
    name = models.CharField(max_length=100, blank=False,verbose_name="כותרת")
    text = models.TextField(max_length=5000, blank=False,verbose_name="תיאור")
    status = models.BooleanField(default=False)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "לוח מטלות"

Taskboard/forms.py
from django.forms import ModelForm
from .models import list_task

class TaskForm(ModelForm):
    class Meta:
        model = list_task
        fields = ['date', 'name', 'text']

Taskboard/views.py
from django.shortcuts import render, redirect
from .models import list_task
from .forms import TaskForm
from django.http import HttpResponse, FileResponse
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
import io
import xlwt


def all_task(request):
    tasks = list_task.objects.all()
    return render(request, 'Taskboard/all_task.html', {'tasks': tasks})


def task_detail(request, id=None):
    task_obj = None
    if id is not None:
        task_obj = list_task.objects.get(id=id)
    context = {"object": task_obj}
    return render(request, 'Taskboard/task_detail.html', context=context)


def createTask(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.save()
            return redirect('Taskboard:all_task')
    return render(request, 'Taskboard/createTask.html', {'form': TaskForm()})


def assignTask(request, id):
    list_task.objects.filter(id=id).update(user=request.user)
    return redirect('Taskboard:all_task')


def doneTask(request, id):
    list_task.objects.filter(id=id).update(status=True)
    return redirect('Taskboard:all_task')

def deleteTask(request, task_id):
    """the function delete a task according to the request of the user (admin only) and delete it
     from the database """
    task = list_task.objects.get(pk=task_id)
    task.delete()  # delete the task from the database
    return redirect('Taskboard:all_task')  # refers to the page of all tasks

def export_pdf(request):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    # creat a text object
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    pdfmetrics.registerFont(TTFont('David', 'David.ttf'))
    textob.setFont("David", 14)

    tasks = list_task.objects.all()  # designate the model
    lines = []  # creat blank link

    for task in tasks:
        lines.append('Date: ' + str(task.date))
        lines.append('Task: ' + task.name[::-1])
        lines.append('Details: ' + task.text[::-1])
        lines.append('Associated to: ' + str(task.user))
        if task.status:
            lines.append('Status: ' + 'המטלה בוצעה'[::-1])
        else:
            lines.append('Status: ' + "המטלה טרם בוצעה"[::-1])
        lines.append('_______________________________________')
        lines.append('    ')

    textob.textLine("Weekly tasks report of the 'Bait Ham' association:")
    textob.textLine("    ")
    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename='tasks.pdf')


def export_excel(request):
    response = HttpResponse(content_type='tasks/excel')
    response['Content-Disposition'] = 'attachment; filename=tasks' + str(datetime.now()) + '.xls'
    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet('tasks')  # give a name to the sheet
    row_num = 2
    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    ws.write(0, 0, 'Weekly tasks report of the "Bait Ham" association:', font_style)

    columns = ['Date', 'Task', 'Details', 'Done?']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    rows = list_task.objects.all().values_list('date', 'name', 'text', 'status')

    font_style = xlwt.XFStyle()

    for row in rows:
        row_num += 1
        for col_num in range(len(row)):
            ws.write(row_num, col_num, str(row[col_num]), font_style)

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    wb.save(response)

    return response

Taskboard/templates/Taskboard/all_task.html
{% extends "adopter/Base.html" %}

{% load static %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <div class="row"/>
    <head>
        <style>
            h1 {
                text-align: center;
            }

            p {
                text-align: center;
            }

            div {
                text-align: center;
            }
        </style>
    </head>
{% if user.is_authenticated %}
    <b>מחובר בתור {{user.username}}</b>
    {% endif %}
    <br>

<br>

<h1 class="font-weight-bold text-center"> לוח מטלות שבועי </h1>
<br>
<br>
    <div>
    {% if user.is_authenticated and user.is_superuser %}
        <br>
        <a role="button" href="{% url 'Taskboard:createTask' %}" class="btn btn-dark">הוסף מטלה</a>
        <br>
        <br>
    {% endif %}
    </div>
<br>
    <br>
{% for task in tasks %}
<div class="col-lg-4 col-md-6">
    <div class="row justify-content-center my-3">

        <h4> <a href= "task_detail/{{task.id}}" >{{ task.name }}</a></h4>
        <p>{{ task.text}}</p>
        <b> משויך ל: {{ task.user.first_name }}</b>
        <br>
        סטטוס:
        <td>{% if task.status == True %}&#10004;{% else %}&times;{% endif %}</td>
        <br>
        <br>
            <hr>

    </div>
</div>
{% endfor %}

{% endblock %}

Taskboard/templates/Taskboard/createTask.html
{% extends 'adopter/Base.html' %}
{% block content %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!doctype html>
<html lang="he" dir="rtl">

    <html>
<head>
<style>
h1 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>
</head>
<body>

    <h1>הוספת מטלה ללוח המטלות</h1>
    <br>
    <form method="POST">
        {% csrf_token %}
    {{ form.as_p }}

        <button type="submit" class="btn btn-dark">הוסף</button>
    </form>

 {% endblock %}

Taskboard/templates/Taskboard/task_detail.html
{% extends "adopter/Base.html" %}
{% load static %}
{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<head>
    <style>
        h1 {
            text-align: center;
        }

        p {
            text-align: center;
        }

        div {
            text-align: center;
        }

    </style>
    <meta charset="UTF-8">

</head>
<body>
<br>
<br>
<a role="button" href="{% url 'Taskboard:assignTask' object.id %}" class="btn btn-secondary"> עליי! </a>
<br>
<br>

<h1>{{object.name}}</h1>
<br>
<ins><h5> תיאור המטלה:</h5></ins>
<b>{{object.text}}</b>
<br>
<br>
<b>משויכת ל:</b>
<b>{{ object.user.first_name }}</b>
<br>
<br>

<br>
<br>
<a role="button" href="{% url 'Taskboard:doneTask' object.id %}" class="btn btn-warning"> מטלה בוצעה? לחץ כאן! </a>

<a role="button" href="{% url 'Taskboard:all_task' %}" class="btn btn-dark"> לכל המטלות </a>

<br>
<br>
{% if user.is_authenticated and user.is_superuser %}
        <a href="{% url 'Taskboard:deleteTask' object.id %}" class="btn btn-dark">מחק מטלה</a>
        {% endif %}
</body>
{% endblock content %}